ARG BASE_REGISTRY=nexus-docker-secure.levelup-dev.io
ARG BASE_IMAGE=ubi/ubi8
ARG BASE_TAG=8.1
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

LABEL name="Jira Software" \
	description="Jira Software Image based on the Red Hat Universal Base Image for DSOP." \
	vendor="Atlassian Software" \
	summary="JiraSoftware (Red Hat UBI)" \
	maintainer="CloudFit Software <brianmiller@cloudfitsoftware.com>" \
	version="8.6.1"


ENV TINI_VERSION=v0.18.0
ENV JIRA_VERSION=8.6.1
ENV ARTEFACT_NAME=atlassian-jira-software
ENV DOWNLOAD_URL https://product-downloads.atlassian.com/software/jira/downloads/${ARTEFACT_NAME}-${JIRA_VERSION}.tar.gz

ENV RUN_USER                                        jira
ENV RUN_GROUP                                       jira
ENV RUN_UID                                         1000
ENV RUN_GID                                         1000

# https://confluence.atlassian.com/display/JSERVERM/Important+directories+and+files
ENV JIRA_HOME                                       /var/atlassian/application-data/jira
ENV BASE_INSTALL_DIR                                /opt/atlassian
ENV JIRA_INSTALL_DIR                                ${BASE_INSTALL_DIR}/jira
ENV SHARED_DIR                                      /mnt/shared

# Installing openjdk creates a symlink at this location
# Using this symlink, the jdk version no longer has to be used in paths
ENV JAVA_HOME /etc/alternatives/jre
ENV JAVA_KEYSTORE  ${JAVA_HOME}/lib/security/cacerts

# Used to import certs into Java keystore
ENV ENABLE_CERT_IMPORT false
ENV SSL_CERTS_DIR ${BASE_INSTALL_DIR}/ssl

RUN yum update --nogpgcheck -y \
    && yum --nogpgcheck -y install fontconfig python3 python3-jinja2 java-1.8.0-openjdk \
    && yum --nogpgcheck -y clean all \
    && rm -rf /var/lib/apt/lists/*

COPY ./tini /tini
COPY ./atlassian-jira-software-8.6.1.tar.gz /tmp/atlassian-jira-software-8.6.1.tar.gz
RUN chmod +x /tini

RUN groupadd -g ${RUN_GID} ${RUN_GROUP} \
    && adduser -u ${RUN_UID} -g ${RUN_GID} -d /usr/share/${RUN_USER} ${RUN_USER} \
    && echo PATH=$PATH > /etc/environment \
    && mkdir -p                                     ${JIRA_HOME} \
    && mkdir -p                                     ${JIRA_INSTALL_DIR} \
    && mkdir -p                                     ${BASE_INSTALL_DIR}/entrypoint \
    && mkdir -p                                     ${BASE_INSTALL_DIR}/support \
    && mkdir -p                                     ${BASE_INSTALL_DIR}/etc \
    && mkdir -p                                     ${SSL_CERTS_DIR} \
    && mkdir -p                                     ${SHARED_DIR} \
    && tar --strip-components=1 -C "${JIRA_INSTALL_DIR}" -zxf /tmp/atlassian-jira-software-8.6.1.tar.gz \
    && chmod -R 700 ${BASE_INSTALL_DIR} ${JIRA_HOME} ${JAVA_KEYSTORE} ${SHARED_DIR} \
    && chown -R ${RUN_USER}:${RUN_GROUP} ${BASE_INSTALL_DIR} ${JIRA_HOME} ${JAVA_KEYSTORE} ${SHARED_DIR} \
    \
    && sed -i -e 's/^JVM_SUPPORT_RECOMMENDED_ARGS=""$/: \${JVM_SUPPORT_RECOMMENDED_ARGS:=""}/g' ${JIRA_INSTALL_DIR}/bin/setenv.sh \
    && sed -i -e 's/^JVM_\(.*\)_MEMORY="\(.*\)"$/: \${JVM_\1_MEMORY:=\2}/g' ${JIRA_INSTALL_DIR}/bin/setenv.sh \
    && sed -i -e 's/-XX:ReservedCodeCacheSize=\([0-9]\+[kmg]\)/-XX:ReservedCodeCacheSize=${JVM_RESERVED_CODE_CACHE_SIZE:=\1}/g' ${JIRA_INSTALL_DIR}/bin/setenv.sh \
    \
    && touch /etc/container_id \
    && chown ${RUN_USER}:${RUN_GROUP}               /etc/container_id

ADD bin                                              ${BASE_INSTALL_DIR}/entrypoint
ADD support                                          ${BASE_INSTALL_DIR}/support
ADD config                                           ${BASE_INSTALL_DIR}/etc

# Expose default HTTP connector port for Jira.
EXPOSE 8080/tcp

# Peer discovery ports for Jira running in cluster mode.
EXPOSE 40001/tcp

WORKDIR ${JIRA_HOME}

USER ${RUN_USER}:${RUN_GROUP}

VOLUME ["${JIRA_HOME}", "${JIRA_INSTALL_DIR}/logs"]

CMD ["/opt/atlassian/entrypoint/entrypoint.py"]
ENTRYPOINT ["/tini", "--"]
